# Generated by Django 4.2.18 on 2025-05-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_classroom_academic_course_and_more'),
        ('students', '0002_alter_student_name_alter_student_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classrooms.classroom'),
        ),
    ]
