# Generated by Django 4.2.18 on 2025-02-15 10:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('province', models.CharField(choices=[('Andalucía', 'Andalucía'), ('Aragón', 'Aragón'), ('Asturias', 'Asturias'), ('Baleares', 'Baleares'), ('Canarias', 'Canarias'), ('Cantabria', 'Cantabria'), ('Castilla-La Mancha', 'Castilla-La Mancha'), ('Castilla y León', 'Castilla y León'), ('Cataluña', 'Cataluña'), ('Extremadura', 'Extremadura'), ('Galicia', 'Galicia'), ('Madrid', 'Madrid'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('País Vasco', 'País Vasco'), ('La Rioja', 'La Rioja'), ('Ceuta', 'Ceuta'), ('Melilla', 'Melilla')], default='Sevilla', max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stages', multiselectfield.db.fields.MultiSelectField(choices=[('Infantil', 'Infantil'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('FP', 'FP'), ('Ciclo Formativo', 'Ciclo Formativo')], default='Primaria', max_length=60)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
