# Generated by Django 4.2.18 on 2025-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='community',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='stages',
            field=models.TextField(max_length=100),
        ),
    ]
