# Generated by Django 4.2.18 on 2025-02-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='province',
            new_name='comunity',
        ),
    ]
