# Generated by Django 4.2.18 on 2025-02-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_rename_province_school_comunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='comunity',
            new_name='community',
        ),
    ]
