# Generated by Django 4.2.18 on 2025-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_comunity_school_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='stages',
            field=models.TextField(max_length=500),
        ),
    ]
