# Generated by Django 4.2.18 on 2025-02-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='community',
            field=models.CharField(max_length=100),
        ),
    ]
