# Generated by Django 4.2.18 on 2025-03-01 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_course', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('academic_year', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_academic_year', message='Academic year must be in the format YYYY-YYYY', regex='^\\d{4}-\\d{4}$')])),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['name'],
            },
        ),
    ]
