# Generated by Django 4.2.18 on 2025-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_add_creator_to_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='academic_course',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
