# Generated by Django 4.2.18 on 2025-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='tag',
            field=models.CharField(choices=[('terms', 'Terms and Conditions of Use'), ('cookies', 'Cookie Policy'), ('privacy', 'Privacy Policy'), ('license', 'License')], default='terms', max_length=20),
        ),
    ]
