# Generated by Django 4.2.18 on 2025-04-01 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_alter_terms_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='pdf_content',
            field=models.FileField(blank=True, null=True, upload_to='terms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
