# Generated by Django 4.2.18 on 2025-03-05 16:52

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_add_creator_to_classroom'),
        ('materials', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='classrooms.classroom', validators=[materials.models.validate_file_limit]),
        ),
    ]
