# Generated by Django 4.2.18 on 2025-03-17 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_add_creator_to_classroom'),
        ('materials', '0004_alter_document_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='classrooms.classroom'),
        ),
    ]
