# Generated by Django 4.2.18 on 2025-03-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('materials', '0004_alter_document_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='tags.tag'),
        ),
    ]
