# Generated by Django 4.2.18 on 2025-03-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_document_classroom'),
        ('materials', '0005_document_tags'),
    ]

    operations = [
    ]
