# Generated by Django 4.2.18 on 2025-05-10 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-30 characters long and contain only letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]{3,30}$')]),
        ),
    ]
